### ISSUE TITLE
Checkout referrals are not being generated

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-checkout-referrals#17]
Referrals are not being generated properly on checkout.

Ticket: https://secure.helpscout.net/conversation/570770402/81272?folderId=634609.

**Comment by michaelbeil** [comment]
I was able to replicate this here: http://s14890.p27.sites.pressdns.com/.

**Comment by amdrew** [comment]
Replicated. Was working fine with AffiliateWP v2.1.15, seems to have broke in v2.1.16.

**Comment by amdrew** [comment]
This stopped working because we removed the `woocommerce_checkout_order_processed` hook:
https://github.com/AffiliateWP/AffiliateWP/pull/2582/files#diff-9da1a461f3f554143b9b37675371bfa9L23

To fix we should be able to just change the hook in Checkout Referrals to `woocommerce_checkout_update_order_meta`.

**Comment by amdrew** [comment]
PR: https://github.com/AffiliateWP/affiliatewp-checkout-referrals/pull/18

@michaelbeil Can you please the PR with both AffiliateWP v2.1.17 and v2.1.7 to make sure referrals work.

**Comment by pippinsplugins** [comment]
I've confirmed the fix.
